export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
export const PERFIL_REPOSITORY = 'PERFIL_REPOSITORY';
export const ACCESO_REPOSITORY = 'ACCESO_REPOSITORY';
export const ROL_REPOSITORY = 'ROL_REPOSITORY';