export const USUARIO_REPOSITORY = 'USUARIO_REPOSITORY';
export const PERFIL_REPOSITORY = 'PERFIL_REPOSITORY';
export const ACCESO_REPOSITORY = 'ACCESO_REPOSITORY';
export const ROL_REPOSITORY = 'ROL_REPOSITORY';
export const PERMISO_REPOSITORY = 'PERMISO_REPOSITORY';
export const DETALLE_PERMISO_REPOSITORY = 'DETALLE_PERMISO_REPOSITORY';